application: ire-scoreboard
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: scoreboard.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest